version: 1.1.{build}

skip_non_tags: true

image: Visual Studio 2019

environment:

  NUGET_API_KEY:

    secure: a1yMnPPhFaMgpXPmwZe5kB5WzhBl5MMEOjAeQO3DmEtzylhJ/hAS8t0Dze16jL0J

build_script:

- ps: dotnet pack DiscordBotTemplates.Discord.Net/DiscordBotTemplates.Discord.Net.csproj

test: off

artifacts:

- path: DiscordBotTemplates.Discord.Net\bin\Release\*.nupkg

  name: dnetpackage

deploy:

- provider: NuGet

  api_key:

    secure: a1yMnPPhFaMgpXPmwZe5kB5WzhBl5MMEOjAeQO3DmEtzylhJ/hAS8t0Dze16jL0J

  skip_symbols: true

  artifact: dnetpackage