version: 2.0.0.{build}

skip_non_tags: true

image: Visual Studio 2019

environment:

  NUGET_API_KEY:

    secure: a1yMnPPhFaMgpXPmwZe5kB5WzhBl5MMEOjAeQO3DmEtzylhJ/hAS8t0Dze16jL0J

build_script:

- ps: $Env:Version += if ($Env:APPVEYOR_REPO_TAG_NAME -eq $null) { $Env:APPVEYOR_BUILD_VERSION } else { $Env:APPVEYOR_REPO_TAG_NAME }
- ps: $Env:VersionSuffix += if ($Env:APPVEYOR_REPO_TAG_NAME -eq $null) { "pre+" + $Env:APPVEYOR_REPO_COMMIT.Substring(0, 8) } else { "" }
- ps: dotnet pack DiscordBotTemplates/DiscordBotTemplates.csproj -p:TemplatesPath=./bin -p:VersionPrefix=$Env:Version -p:VersionSuffix=$Env:VersionSuffix

test: off

artifacts:

- path: DiscordBotTemplates\bin\*.nupkg

  name: templates

deploy:

- provider: NuGet

  api_key:

    secure: kWzmUr9Hg/i59uqUmZh/bd2fQFpoF+IhQnCQViO3xGhlwAGg1/6gwn9g7mvePMAD

  skip_symbols: true

  artifact: templates