name: NuGet Deploy (Release)

on:
  release:
    types: [ released ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack templates
        run: dotnet pack -c Release DiscordBotTemplates/DiscordBotTemplates.csproj

      - name: Upload templates
        run: dotnet nuget push DiscordBotTemplates/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json